export const words = [
  'Cat',
  'Dog',
  'House',
  'Tree',
  'Car',
  'Book',
  'Chair',
  'Apple',
  'Ball',
  'Sun',
  'Water',
  'Time',
  'Person',
  'Food',
  'Love',
  'Day',
  'Money',
  'Music',
  'Sleep',
  'Sky',
  'Bird',
  'Flower',
  'Friend',
  'Game',
  'Hat',
  'Job',
  'Key',
  'Moon',
  'Nose',
  'Ocean',
  'Picture',
  'Queen',
  'Rain',
  'School',
  'Table',
  'Umbrella',
  'Voice',
  'Window',
  'Year',
  'Zoo',
  'Lamp',
  'Pen',
  'Phone',
  'Cup',
  'Shirt',
  'Road',
  'Bridge',
  'Smile',
  'Sunflower',
  'Bicycle',
  'Dance',
  'Fruit',
  'Mountain',
  'Pencil',
  'Star',
  'Train',
  'Rainbow',
  'Chair',
  'Computer',
  'Beach',
  'Camera',
  'Guitar',
  'Fire',
  'Soccer',
  'Elephant',
  'Robot',
  'Pizza',
  'Television',
  'Clock',
  'Horse',
];

export const wordsToSpanish = {
  cat: 'gato',
  dog: 'perro',
  house: 'casa',
  tree: 'árbol',
  camera: 'camara',
  soccer: 'messi',
  computer: 'computadora',
  pizza: 'pizza',
  fire: 'Fuego',
  car: 'coche',
  book: 'libro',
  chair: 'silla',
  apple: 'manzana',
  ball: 'pelota',
  sun: 'sol',
  water: 'agua',
  time: 'tiempo',
  person: 'persona',
  food: 'comida',
  love: 'amor',
  day: 'día',
  horse: 'Caballo',
  television: 'Television',
  guitar: 'guitarra',
  money: 'dinero',
  music: 'música',
  sleep: 'dormir',
  sky: 'cielo',
  bird: 'pájaro',
  flower: 'flor',
  friend: 'amigo',
  game: 'juego',
  hat: 'sombrero',
  job: 'trabajo',
  key: 'llave',
  moon: 'luna',
  nose: 'nariz',
  ocean: 'océano',
  picture: 'imagen',
  queen: 'reina',
  rain: 'lluvia',
  school: 'escuela',
  table: 'mesa',
  umbrella: 'paraguas',
  voice: 'voz',
  window: 'ventana',
  year: 'año',
  zoo: 'zoológico',
  lamp: 'lámpara',
  pen: 'pluma',
  phone: 'teléfono',
  cup: 'taza',
  shirt: 'camisa',
  road: 'camino',
  bridge: 'puente',
  smile: 'sonrisa',
  sunflower: 'girasol',
  bicycle: 'bicicleta',
  dance: 'danza',
  fruit: 'fruta',
  mountain: 'montaña',
  pencil: 'lápiz',
  star: 'estrella',
  train: 'tren',
  rainbow: 'arcoíris',
};
